version: "0.2"
language: en
words:
  - addnab
  - armv
  - autoupdate
  - binstall
  - bndy
  - capfd
  - cdylib
  - clippy
  - Doherty
  - dtolnay
  - endfor
  - endmacro
  - getattr
  - gnueabi
  - gnueabihf
  - hustcer
  - isnan
  - libc
  - libnghttp
  - manylinux
  - maturin
  - msvc
  - multiarch
  - mypy
  - napi
  - nextest
  - nonconstructor
  - nonoctal
  - npmjs
  - nushell
  - orhun
  - oxlint
  - patchelf
  - pyclass
  - pyfunction
  - pymethods
  - pymodule
  - pypa
  - pypi
  - pyproject
  - pytest
  - repr
  - rustc
  - rustflags
  - rustup
  - sccache
  - sdist
  - staticlib
  - taiki
  - timeit
  - topo
  - venv
  - zigbuild
ignorePaths:
  - .env/**
  - .venv/**
  - env/**
  - venv/**
  - target/**
  - "**/.gitignore"
  - .yarn/releases/*
