[project]
name = "mk-pass-ws"
version = "0.0.0+private-virtual"
requires-python = ">=3.9"
dependencies = ["mk-pass"]

[tool.uv.sources]
mk-pass = { workspace = true }

[tool.uv.workspace]
members = ["bindings/python"]
